language: node_js
node_js:
- 7
branches:
  only:
  - digitalocean
env:
  global:
  - REMOTE_PATH=/home/deployment/deploy/FinderLocals-Backend
  - REMOTE_USER=deployment
  - REMOTE_HOST=142.93.171.171
before_install:
- openssl aes-256-cbc -K $encrypted_46ddb366c807_key -iv $encrypted_46ddb366c807_iv
  -in sshTravis.enc -out sshTravis -d
- eval "$(ssh-agent -s)"
- chmod 600 sshTravis
- ssh-add sshTravis
after_success:
- bash scripts/deploy.sh