version: ‘3.1’
services:
  db:
    image: mariadb:10.318-bionic
    - dbdata:/var/lib/mariadb 
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: : mariadb
    MYSQL_DATABASE: mariadb
    MYSQL_USER: mariadb
    MYSQL_PASSWORD: mariadb
  node:
    depends_on:
      -db
    image: mhart/alpine-node:13.0
    ports:
      - 8000:80
    restart: always
    volumnes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    image: nginx:1.17.5-alpine
    ports:
      - 8000:80
    restart: always
    volumes: 
      - /usr/share/nginx/html
volumes:
dbdata: