version: ‘3.1’
services:
  db:
    image: mongo:3.4.23-xenial
    - dbdata:/var/lib/mongodb 
  restart: always
  environment:
    - MONGO_INITDB_DATABASE: mongodb
    - MONGO_INITDB_ROOT_USERNAME: mongodb
    - MONGO_INITDB_ROOT_PASSWORD: mongodb
  node:
    depends_on:
      -db
    image: mhart/alpine-node:13.0
    ports:
      - 8000:80
    restart: always
    volumnes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    image: nginx:1.17.5-alpine
    ports:
      - 8000:80
    restart: always
    volumes: 
      - /usr/share/nginx/html
volumes:
dbdata: